### PR TITLE
add function for right-box-actor-added-signal

### PR DESCRIPTION
**Pull request by pratap-panabaka**
Hi @dantehemerson I have gone through the code for actor-added signal and made a function to check if right-box is selected and according to that adding the signal if actor added. Tested the code by adding the actor to right box and checked for the persistence of one-thing index. It is working.

### CODE REVIEW

**Review by dantehemerson — APPROVED** [review]
LGTM!

**Comment by dantehemerson** [comment]
Great, let's send this!

**Comment by dantehemerson** [comment]
@PRATAP-KUMAR New version approved, well done! https://extensions.gnome.org/review/47332

**Comment by PRATAP-KUMAR** [comment]
@dantehemerson Hi, Can I have your email Id?

**Comment by dantehemerson** [comment]
Sure, here is `dantecalderon.dev [at] gmail.com`

**Comment by PRATAP-KUMAR** [comment]
@dantehemerson Hi Dante, you can delete your msg above.

**Pull request merged**
