### PR TITLE
Add Keybinding Super+W

### LINKED ISSUE #9: Suggestion: show how to set one-thing value in README
This is such a ONE-derful extension, thank you!

I am using it daily, and have connected it to my workflow. Here is how I set the value in the menu bar from the command line:

```
dconf write /org/gnome/shell/extensions/one-thing/thing-value "'My todo'"
```

I'm using it in Wayland to copy the clipboard to One Thing like so:

```
dconf write /org/gnome/shell/extensions/one-thing/thing-value "'$(wl-paste|sed "s/'/\\\'/g")'"
```

Perhaps others can benefit from this also. Thanks!

### LINKED ISSUE #10: Suggestion: Thing text selected by default on Edit Task dialog open
My suggestion is that when the "Edit task" dialog is opened, the text would be selected by default.

This would allow the user to immediately start typing a new "thing" and hit Enter to set it, without the need to delete delete the existing text.

It shouldn't prevent the user from clicking on any other UI element if that was his intent.

Also, thanks for a great simple add-on

### LINKED ISSUE #11: Suggestion: Add support to assigning a hotkey for opening Edit Task dialog
The suggestion is to add support to assigning a hotkey to opening the Edit Task dialog.

Together with https://github.com/one-thing-gnome/one-thing/issues/10 this would allow for the main user flow of this extention to be minimal effort for keyboard centric users:

To change the Thing, from anywhere, you'd only need to type `<hotkey>` `<Text for new Thing>` `[Enter]`

Also, thanks for a great simple add-on

### PR DESCRIPTION
**Pull request by pratap-panabaka**
Hi,
I have implemented keyboard shortcut Alt+W to open the One Thing.

Above implementation also allows to focus on writing one-thing via CTRL+ALT+TAB Top-bar, navigate to one-thing and hit enter.

one-thing

Thanks.

### CODE REVIEW

**Review by dantehemerson — APPROVED** [review]
LGTM!

**Comment by pratap-panabaka** [comment]
Hi @dantehemerson with this branch, it is possible to close all the 3 issues on this repo. Once this extension is approved, then we can close those 3 issues.

Thanks

**Review by kra-mo — CHANGES_REQUESTED** [review]
Alt is a modifier key used by applications. I suggest using Super.

There should also be a way to at least turn the shortcut off, though it would be best if it would be configurable.

**Comment by pratap-panabaka** [comment]
Hi @kra-mo.
Nice to see your points on this review request.

I have changed the hotkey from `Alt+W` to `Super+W`.
Added the switch for turning off the hot key. By default hot key is turned on.

HotKey(Super+W)

I will take some time to understand how to implement the hot key configurable by user. I dont find a way to make it like creating the keyboard shortcut. via dconf command line it is possible to configure the hot key but that will be like trail n error for me. I need to understand it. If you can help me with this, I will be thankful to you.

Mean while can we go for extension's review process through @dantehemerson?

Thanks

**Comment by kra-mo** [comment]
You can take a look at [Pano's implementation](https://github.com/oae/gnome-shell-pano/blob/master/src/prefs/general/shortcutRow.ts) for registering a keyboard shortcut. I think it would be best not to ship this feature without it being configurable.

**Comment by dantehemerson** [comment]
I agree with @kra-mo, let's make it configurable before send to review.

**Comment by pratap-panabaka** [comment]
Hi @kra-mo @dantehemerson.

I tired my best to implement the keybinding UI feature with the help of Pano's Implementation.
Please adjust the code if you feel any improvement is required.

image

Thanks!

**Review by kra-mo — APPROVED** [review]

**Comment by kra-mo** [comment]
LGTM, thanks!

**Review by dantehemerson — APPROVED** [review]
LGTM! Thanks @PRATAP-KUMAR , I will send it for review

**Comment by dantehemerson** [comment]
Here is the link the the review: https://extensions.gnome.org/review/47935

**Comment by pratap-panabaka** [comment]
> Here is the link the the review: https://extensions.gnome.org/review/47935

@dantehemerson Hi, How are you

I have visited review page and found two comments from gnome-extensions reviewer.
Implemented them. Please have a review on it and then you can submit.

Thanks

**Comment by dantehemerson** [comment]
Hi @PRATAP-KUMAR , Great! 

I just sent it to review https://extensions.gnome.org/review/48379

**Comment by dantehemerson** [comment]
@PRATAP-KUMAR we received a review on this: https://extensions.gnome.org/review/48379. A change is required.

**Comment by pratap-panabaka** [comment]
Hi @dantehemerson I have corrected it on the same day when I saw that. Plz check for that line in main brach and proceed to upload. Thanks

**Comment by dantehemerson** [comment]
@PRATAP-KUMAR The updates were approved! https://extensions.gnome.org/review/51630

**Pull request merged**
