### PR TITLE
feat: Show icon on empty text

### PR DESCRIPTION
**Pull request by dantehemerson**
Related to: https://github.com/one-thing-gnome/one-thing-prev/pull/6

### CODE REVIEW

**Comment by dantehemerson** [comment]
@kra-mo @jancborchardt I added the functionality to show icon if the text is empty based on https://github.com/one-thing-gnome/one-thing-prev/pull/6.
Let me hear your thoughts on this and if anything is missing.

**Review by pratap-panabaka — CHANGES_REQUESTED** [review]
Edited this content.

**Comment by PRATAP-KUMAR** [comment]
@dantehemerson I have created schemas file and app is working but icon is not visible on empty text.

**Review by pratap-panabaka — APPROVED** [review]
Good Job @dantehemerson

The icon on empty text is shining..



Status: Approved :green_circle:

You can merge it now

Cheers :beers: 
Happy Coding!!!

**Comment by dante-calderon** [comment]
@PRATAP-KUMAR Thank for your review, it's good to know that it's working for you. I will merge it and publish a new version.

**Comment by dantehemerson** [comment]
@PRATAP-KUMAR Thank you for your review, it's good to know that it's working for you. I will merge it and publish a new version.

**Comment by pratap-panabaka** [comment]
@dantehemerson thank you for your reply. I am happy to be part of this extension. I have bit of UI suggestions that I will propose in a day or two.

**Pull request merged**
